//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class blog
{
    public blog()
    {
        this.comments = new HashSet<comments>();
    }

    public int ID { get; set; }
    public string title { get; set; }
    public string describe { get; set; }
    public string text { get; set; }
    public int StudentID { get; set; }
    public System.DateTime time { get; set; }

    public virtual users users { get; set; }
    public virtual ICollection<comments> comments { get; set; }
}

public partial class blog_c
{
    public int ID { get; set; }
    public int articleID { get; set; }
    public int accountID { get; set; }
    public System.DateTime time { get; set; }
    public string name1 { get; set; }
    public string text { get; set; }
}

public partial class blog_user
{
    public int ID { get; set; }
    public string title { get; set; }
    public string describe { get; set; }
    public string text { get; set; }
    public string name1 { get; set; }
    public System.DateTime time { get; set; }
    public int StudentID { get; set; }
}

public partial class comment2
{
    public int id { get; set; }
    public int commentID { get; set; }
    public int accountID { get; set; }
    public System.DateTime time { get; set; }
    public string text { get; set; }

    public virtual comments comments { get; set; }
}

public partial class comments
{
    public comments()
    {
        this.comment2 = new HashSet<comment2>();
    }

    public int ID { get; set; }
    public int articleID { get; set; }
    public int accountID { get; set; }
    public System.DateTime time { get; set; }
    public string text { get; set; }

    public virtual blog blog { get; set; }
    public virtual ICollection<comment2> comment2 { get; set; }
    public virtual users users { get; set; }
}

public partial class picture
{
    public int ID { get; set; }
    public string files { get; set; }
    public int accountID { get; set; }
    public System.DateTime time { get; set; }

    public virtual users users { get; set; }
}

public partial class picture_u
{
    public int ID { get; set; }
    public string files { get; set; }
    public System.DateTime time { get; set; }
    public int accountID { get; set; }
    public string name1 { get; set; }
}

public partial class users
{
    public users()
    {
        this.blog = new HashSet<blog>();
        this.comments = new HashSet<comments>();
        this.picture = new HashSet<picture>();
    }

    public int ID { get; set; }
    public string account { get; set; }
    public string password { get; set; }
    public string name1 { get; set; }

    public virtual ICollection<blog> blog { get; set; }
    public virtual ICollection<comments> comments { get; set; }
    public virtual ICollection<picture> picture { get; set; }
}
