//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class blogEntities : DbContext
{
    public blogEntities()
        : base("name=blogEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<blog> blog { get; set; }
    public DbSet<comment2> comment2 { get; set; }
    public DbSet<comments> comments { get; set; }
    public DbSet<picture> picture { get; set; }
    public DbSet<users> users { get; set; }
    public DbSet<blog_c> blog_c { get; set; }
    public DbSet<blog_user> blog_user { get; set; }
    public DbSet<picture_u> picture_u { get; set; }
}
